spring:
  application:
    name: LoginUser

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_role_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true


server:
  port: 8080

