spring:
  application:
    name: TableTesting

  datasource:
    url: jdbc:mysql://localhost:3306/Day5?useSSL=false&serverTimezone=UTC
    username: root
    password: f1309D1309@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
