spring:
  application:
    name: testing2
  datasource:
    url: jdbc:mysql://localhost:3306/testing2
    username: root
    password: f1309D1309@

  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

