spring:
  application:
    name: StoreApp
  datasource:
    url: jdbc:postgresql://localhost:5432/storeapp
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
    - classpath:db/migration

server:
  port: 8080