spring:
  application:
    name: RoleBasedProject
  
  datasource:
    url: jdbc:postgresql://localhost:5432/rolebased
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations:
    - classpath:db/migration

server:
  port: 8080

